### ISSUE TITLE
yarn install in readme

### ISSUE THREAD

**Issue by DanielRuf** [proophboard/ts-cody-tutorial#1]
`yarn install` is mentioned in the readme. But this breaks the setup because yarn does not fully support the package-lock.json file of npm.

Best is to remove the `yarn install` command from the readme or to add a yarn.lock file which has the exact same dependencies and dependency versions.

`yarn import` might be some help.

To see what I mean:
* run `yarn` (alias of `yarn install`)
* run `yarn cody`
* see the errors

![grafik](https://user-images.githubusercontent.com/827205/227526857-2bf77bd1-4997-485a-a7de-572b5f19f6ea.png)

**Comment by codeliner** [comment]
good catch! I'll check it

**Comment by codeliner** [comment]
went for the easy fix and removed yarn commands from README ;)
Thx for pointing this out!
